AWSTemplateFormatVersion: 2010-09-09
Description: "Creates an IAM user for Stelligent-U Topic 3: IAM Practice 3.1.4"
Resources: 
  TheBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Join ['-', [!Ref AWS::Region, !Ref AWS::AccountId, 'thebucketbucketgg']]
  iamRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: bgariamlabrole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS: arn:aws:iam::324320755747:user/brandon.garcia.labs
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
Outputs:
  RoleARN:
    Description: The ARN of the created IAM policy
    Value: !GetAtt iamRole.Arn
    Export:
      Name: !Join [ "-", [ !Ref "AWS::StackName", RoleARN ] ]