AWSTemplateFormatVersion: 2010-09-09
Description: "Creates an IAM user for Stelligent-U Topic 3: IAM Practice 3.1.3"
Resources: 
  iamRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: bgariamlabrole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'
  LabIAMRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: bgariamrole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'
  iamPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties: 
      Description: "Managed policy for bgar IAM lab, multiple roles"
      ManagedPolicyName: bgariamlab
      PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - iam:Get*
            - iam:List*
            Resource:
            - '*'
      Roles: 
        - !Ref iamRole
        - !Ref LabIAMRole
