AWSTemplateFormatVersion: 2010-09-09
Description: "Creates SSM resources for Stelligent-U Topic 11: SSM Practice 11.1.1"
#######
#######
Parameters: 
  EngineerName:
    Description: The engineer's name as first-last(no caps, all lower, hyphenated)
    Type: String
    AllowedPattern: '^[a-z]+-[a-z]+$'
    Default: 'first-last'
    MinLength: 1
    MaxLength: 2048
  EngineerTitle:
    Description: The engineer's title
    Type: String
    Default: 'Important Job'
  EngineerAddress:
    Description: The engineer's address
    Type: String
    Default: '1234 Address Lane'
  EngineerTeamName:
    Description: The engineer's team name
    Type: String
    Default: 'team'
  EngineerTimezone:
    Description: The engineer's time zone
    Type: String
    AllowedPattern: '^[a-zA-Z]*$'
    Default: 'Eastern'
  EngineerStateCode:
    Description: The engineer's two letter state code
    Type: String
    AllowedPattern: '^[a-zA-Z]{2}$'
    Default: 'CA'
  EngineerStartDate:
    Description: The engineer's start date in MM-DD-YYYY format
    Type: String
    AllowedPattern: '^[0-9]{2}-[0-9]{2}-[0-9]{4}$'
    Default: '01-01-2001'
#######
#######
Resources: 
  EngineerNameSSMParameter:
    Type: AWS::SSM::Parameter
    Properties: 
      Description: The name of the engineer
      Name: !Sub /${EngineerName}/name
      Type: String
      Value: !Join [" ", !Split ["-", !Ref EngineerName]]
  EngineerTitleSSMParameter:
    Type: AWS::SSM::Parameter
    Properties: 
      Description: The title of the engineer
      Name: !Sub /${EngineerName}/title
      Type: String
      Value: !Ref EngineerTitle
  EngineerAddressSSMParameter:
    Type: AWS::SSM::Parameter
    Properties: 
      Description: The address of the engineer
      Name: !Sub /${EngineerName}/address
      Type: String
      Value: !Ref EngineerAddress
  EngineerTeamNameSSMParameter:
    Type: AWS::SSM::Parameter
    Properties: 
      Description: The timezone of the engineer
      Name: !Sub /${EngineerName}/team
      Type: String
      Value: !Ref EngineerTeamName
  EngineerTimezoneSSMParameter:
    Type: AWS::SSM::Parameter
    Properties: 
      Description: The timezone of the engineer
      Name: !Sub /${EngineerName}/timezone
      Type: String
      Value: !Ref EngineerTimezone
  EngineerStateCodeSSMParameter:
    Type: AWS::SSM::Parameter
    Properties: 
      Description: The two letter state code where the engineer resides
      Name: !Sub /${EngineerName}/state
      Type: String
      Value: !Ref EngineerStateCode
  EngineerStartDateSSMParameter:
    Type: AWS::SSM::Parameter
    Properties: 
      Description: The date of the engineer's first day of work
      Name: !Sub /${EngineerName}/start-date
      Type: String
      Value: !Ref EngineerStartDate
#######
#######
Outputs:
  EngineerName:
    Description: The SSM parameter storing the engineer's name
    Value: !Ref EngineerNameSSMParameter
  EngineerTitle:
    Description: The SSM parameter storing the engineer's title
    Value: !Ref EngineerTitleSSMParameter
  EngineerAddress:
    Description: The SSM parameter storing the engineer's address
    Value: !Ref EngineerAddressSSMParameter
  EngineerTeamName:
    Description: The SSM parameter storing the engineer's address
    Value: !Ref EngineerTeamNameSSMParameter
  EngineerTimezone:
    Description: The SSM parameter storing the engineer's timezone
    Value: !Ref EngineerTimezoneSSMParameter
  EngineerStateCode:
    Description: The SSM parameter storing state code for where the engineer resides
    Value: !Ref EngineerStateCodeSSMParameter
  EngineerStartDate:
    Description: The SSM parameter storing the engineer's first day of work
    Value: !Ref EngineerStartDateSSMParameter
