AWSTemplateFormatVersion: 2010-09-09
Description: "Creates EC2 resource for Stelligent-U Topic 5: VPC Practice 5.1.2"
Parameters: 
    LatestUbuntuAmiId:
        Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
        Default: '/aws/service/canonical/ubuntu/server/18.04/stable/current/amd64/hvm/ebs-gp2/ami-id'
    LatestWindows2016AmiId:
        Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
        Default: '/aws/service/ami-windows-latest/Windows_Server-2016-English-Full-Base'
    LatestWindows2012R2AmiId:
        Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
        Default: '/aws/service/ami-windows-latest/Windows_Server-2012-R2_RTM-English-64Bit-Base'
    EC2KeyPairName:
      Description: 'The key to use for the instance'
      Type: String
      Default: ''
Resources: 
  EC2Template:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: EC22012R2
      LaunchTemplateData: 
        KeyName: !Ref EC2KeyPairName
        InstanceType: t2.micro
        NetworkInterfaces:
          - SubnetId: !ImportValue bgar-lab-subnet-id
            DeviceIndex: 0
  2012R2Instance:
    Type: AWS::EC2::Instance
    Properties:
      LaunchTemplate: 
        LaunchTemplateId: !Ref EC2Template
        Version: !GetAtt EC2Template.LatestVersionNumber
      ImageId: !Ref LatestWindows2012R2AmiId
      Tags: 
        - Key: Name
          Value: bgar-2012R2-lab51
        - Key: user
          Value: brandon.garcia.labs
        - Key: stelligent-u-lesson
          Value: '5.1'
        - Key: stelligent-u-lab
          Value: '5.1.2'
  2016Instance:
    Type: AWS::EC2::Instance
    Properties:
      LaunchTemplate: 
        LaunchTemplateId: !Ref EC2Template
        Version: !GetAtt EC2Template.LatestVersionNumber
      ImageId: !Ref LatestWindows2016AmiId
      Tags: 
        - Key: Name
          Value: bgar-2016-lab51
        - Key: user
          Value: brandon.garcia.labs
        - Key: stelligent-u-lesson
          Value: '5.1'
        - Key: stelligent-u-lab
          Value: '5.1.2'
  UbuntuInstance:
    Type: AWS::EC2::Instance
    Properties:
      LaunchTemplate: 
        LaunchTemplateId: !Ref EC2Template
        Version: !GetAtt EC2Template.LatestVersionNumber
      ImageId: !Ref LatestUbuntuAmiId
      Tags: 
        - Key: Name
          Value: bgar-Ubuntu-lab51
        - Key: user
          Value: brandon.garcia.labs
        - Key: stelligent-u-lesson
          Value: '5.1'
        - Key: stelligent-u-lab
          Value: '5.1.2'
Outputs:
  2012R2InstanceId:
    Description: The 2012R2 instance id
    Value: !Ref 2012R2Instance
  2012R2PrivateIp:
    Description: The 2012R2 instance private ip
    Value: !GetAtt 2012R2Instance.PrivateIp
  2016InstanceId:
    Description: The 2016 instance id
    Value: !Ref 2016Instance
  2016PrivateIp:
    Description: The 2016 instance private ip
    Value: !GetAtt 2016Instance.PrivateIp
  UbuntuInstanceId:
    Description: The Ubuntu instance id
    Value: !Ref UbuntuInstance
  UbuntuPrivateIp:
    Description: The Ubuntu instance private ip
    Value: !GetAtt UbuntuInstance.PrivateIp