AWSTemplateFormatVersion: 2010-09-09
Description: "Creates an S3 bucket for Stelligent-U Topic 1: CF Practice 1.1"
Resources:
  TheBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Join ['-', [!Ref AWS::Region, !Ref AWS::AccountId, !Ref BucketName]]
Parameters:
  BucketName:
    Description: The name of the bucket
    Type: String
    Default: 'friendly-name'