AWSTemplateFormatVersion: 2010-09-09
Description: "Creates an S3 bucket for Stelligent-U Topic 1: CF Practice 1.2"
Resources:
  TheBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
Parameters:
  BucketName:
    Description: The name of the bucket
    Type: String
    Default: ''