AWSTemplateFormatVersion: 2010-09-09
Description: 'Creates log resources for Stelligent-U Topic 8: Lab 8.2.1'
Parameters: 
  logGroupName:
    Description: 'The name of the log group'
    Type: String
    Default: ''
  logBucketName:
    Description: 'The name of the log group'
    Type: String
    Default: ''
Resources: 
  labLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      RetentionInDays: 60
      LogGroupName: !Ref logGroupName
  s3Bucket:
    Type: AWS::S3::Bucket
    Properties: 
      AccessControl: LogDeliveryWrite
      BucketName: !Ref logBucketName
      Tags: 
        - Key: user
          Value: brandon.garcia.labs
        - Key: stelligent-u-lesson
          Value: '8.2'
        - Key: stelligent-u-lab
          Value: '8.2.1'
  TrailBucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref s3Bucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Sid: AWSCloudTrailAclCheck
          Effect: Allow
          Principal:
            Service: 'cloudtrail.amazonaws.com'
          Action: 's3:GetBucketAcl'
          Resource: !Sub 'arn:aws:s3:::${s3Bucket}'
        - Sid: AWSCloudTrailWrite
          Effect: Allow
          Principal:
            Service: 'cloudtrail.amazonaws.com'
          Action: 's3:PutObject'
          Resource: !Sub 'arn:aws:s3:::${s3Bucket}/logs/*'
  labLogRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - cloudtrail.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Policies:
        - PolicyName: "CloudTrailPut"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action: "logs:CreateLogStream"
                Resource: "*"
              - Effect: "Allow"
                Action: "logs:PutLogEvents"
                Resource: "*"
        - PolicyName: "SNSPut"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action: "sns:*"
                Resource: "*"
  cloudTrail:
    Type: AWS::CloudTrail::Trail
    DependsOn: TrailBucketPolicy
    Properties:
      S3BucketName: !Ref s3Bucket
      CloudWatchLogsLogGroupArn: !GetAtt labLogGroup.Arn
      CloudWatchLogsRoleArn: !GetAtt labLogRole.Arn
      IncludeGlobalServiceEvents: true
      IsLogging: true
      S3KeyPrefix: logs
  SnsTopicMetricFilterCloudWatchAlarm:
    Type: "AWS::SNS::Topic"
    Properties:
      Subscription:
        - Endpoint: "brandon.garcia@stelligent.com"
          Protocol: "email"
  CloudWatchAlarm:
    Type: "AWS::CloudWatch::Alarm"
    Properties:
      AlarmName: "ec2_changes"
      AlarmDescription: "A CloudWatch Alarm that triggers when changes are made to EC2 Instances."
      MetricName: "EC2InstanceEventCount"
      Namespace: "CloudTrailMetrics"
      Statistic: "Sum"
      Period: "60"
      EvaluationPeriods: "1"
      Threshold: "1"
      ComparisonOperator: "GreaterThanOrEqualToThreshold"
      AlarmActions:
        - !Ref "SnsTopicMetricFilterCloudWatchAlarm"
      TreatMissingData: "notBreaching"
  MetricFilterCloudWatchAlarm:
    Type: "AWS::Logs::MetricFilter"
    Properties:
      LogGroupName: !Ref labLogGroup
      FilterPattern: "{ ($.eventName = RunInstances) || ($.eventName = RebootInstances) || ($.eventName = StartInstances) || ($.eventName = StopInstances) || ($.eventName = TerminateInstances) }"
      MetricTransformations:
        - MetricValue: "1"
          MetricNamespace: "CloudTrailMetrics"
          MetricName: "EC2InstanceEventCount"
Outputs:
  Bucket:
    Description: The bucket
    Value: !Ref s3Bucket
  LogGroup:
    Description: The log group
    Value: !Ref labLogGroup