AWSTemplateFormatVersion: 2010-09-09
Description: 'Creates DDB application resources for the child pipeline created in Stelligent-U Topic 12: CodePipeline - Lab 12.2.1'
#######
#######
Parameters: 
  DDBTableName:
    Description: The name of the dynamodb table
    Type: String
    Default: ''
  ApplicationRoleName:
    Description: The name of the application role
    Type: String
    Default: ''
#######
#######
Resources: 
  ApplicationRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonDynamoDBReadOnlyAccess
  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: ids
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      TableName: !Ref DDBTableName
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      Tags: 
        - Key: user
          Value: brandon.garcia.labs
        - Key: stelligent-u-lesson
          Value: '12.2'
        - Key: stelligent-u-lab
          Value: '12.2.1'

#######
#######
Outputs:
  ApplicationRoleName:
    Value: !Ref ApplicationRole
  ApplicationRoleArn:
    Value: !GetAtt ApplicationRole.Arn
  DDBTable:
    Value: !Ref DynamoDBTable