AWSTemplateFormatVersion: 2010-09-09
Description: "Creates CodePipeline resources for Stelligent-U Topic 12: CodePipeline Practice 12.1.1"
######
######
Parameters: 
  BucketName:
    Type: String 
    Default: ''
    Description: The name of the bucket to house pipeline execution state
  ChildBucketName:
    Type: String 
    Default: ''
    Description: The name of the bucket to be deployed in the pipeline
  GitHubOwner:
    Description: The user to pull the repository
    Type: String
    Default: ''
  Branch:
    Description: The branch to pull for pipeline execution
    Type: String
    Default: ''
  RepositoryName:
    Description:  The repository to pull for pipeline execution
    Type: String
    Default: ''
  ValidateProjectName:
    Description:  The name of the validation CodeBuild project
    Type: String
    Default: ''
  TestProjectName:
    Description:  The name of the test CodeBuild project
    Type: String
    Default: ''
  ChildStackName:
    Description:  The name of the stack to be created in the pipeline
    Type: String
    Default: ''
  TemplateFileLocation:
    Description:  The location of the template file within the artifact
    Type: String
    Default: ''
  ChildStackFileLocation:
    Description:  The location of the template file within the artifact
    Type: String
    Default: ''
  ChildStackTemplateConfigurationFileLocation:
    Description:  The name of the application role to be created in the child pipeline
    Type: String
    Default: ''
######
######
Resources: 
  Bucket:
    Type: AWS::S3::Bucket
    Properties: 
      AccessControl: BucketOwnerFullControl
      BucketName: !Ref BucketName
  CodeExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codepipeline.amazonaws.com
                - codebuild.amazonaws.com
            Action:
              - 'sts:AssumeRole'
          - Effect: Allow
            Principal:
              AWS: "arn:aws:iam::324320755747:user/brandon.garcia.labs"
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSCloudFormationFullAccess
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::aws:policy/AWSCodeBuildAdminAccess
        - arn:aws:iam::aws:policy/AWSCodePipeline_FullAccess
        - arn:aws:iam::aws:policy/CloudWatchLogsFullAccess
      Policies:
        - PolicyName: AllowIamActions
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - iam:GetRole
                  - iam:PassRole
                Resource: !GetAtt CloudFormationExecutionRole.Arn
  CloudFormationExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: bgar-stelu-lab12-2-2-CloudFormationExecutionRole-27E9YI21BMOI
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - cloudformation.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::aws:policy/IAMFullAccess
        - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess
  CodePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: !Sub bgar-pipeline
      RoleArn: !GetAtt CodeExecutionRole.Arn
      ArtifactStore:
        Type: S3
        Location: !Ref Bucket
      Stages: 
        - Name: source
          Actions:
            - Name: PullSource
              RunOrder: 1
              ActionTypeId: 
                Category: Source
                Owner: ThirdParty
                Provider: GitHub
                Version: 1
              OutputArtifacts:
                - Name: LabSource
              Configuration: 
                Owner: !Ref GitHubOwner
                Repo: !Ref RepositoryName
                Branch: !Ref Branch
                OAuthToken: "{{resolve:secretsmanager:bgar-gh-token:SecretString:::7de73ed0-8301-4895-99b0-b6dda7da39d9}}"
                PollForSourceChanges: true
        - Name: deploy
          Actions:
            - Name: CreateChangeSet
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: 1
              InputArtifacts: 
                - Name: LabSource
              Configuration:
                Capabilities: CAPABILITY_NAMED_IAM
                TemplateConfiguration: !Sub LabSource::${ChildStackTemplateConfigurationFileLocation}
                ActionMode: CHANGE_SET_REPLACE
                RoleArn: !GetAtt CloudFormationExecutionRole.Arn
                StackName: !Ref ChildStackName
                TemplatePath: !Sub LabSource::${ChildStackFileLocation}
                ChangeSetName: lab-change-set
            - Name: ExecuteChangeSet
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: 1
              InputArtifacts: 
                - Name: LabSource
              Configuration:
                Capabilities: CAPABILITY_NAMED_IAM
                TemplateConfiguration: !Sub LabSource::${ChildStackTemplateConfigurationFileLocation}
                ActionMode: CHANGE_SET_EXECUTE
                RoleArn: !GetAtt CloudFormationExecutionRole.Arn
                StackName: !Ref ChildStackName
                TemplatePath: !Sub LabSource::${ChildStackFileLocation}
                ChangeSetName: lab-change-set
      RestartExecutionOnUpdate: false
  ValidateBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Ref ValidateProjectName
      Description: build project to validate our CF Template
      ServiceRole: !GetAtt  CodeExecutionRole.Arn
      Artifacts:
          Type: CODEPIPELINE
      Environment:
          Type: LINUX_CONTAINER
          ComputeType: BUILD_GENERAL1_SMALL
          Image: aws/codebuild/standard:4.0
          PrivilegedMode: true  
      Source:
          Type: CODEPIPELINE
          BuildSpec: !Sub |
            version: 0.2
            phases:
              install:
                commands:
                  - pip3 install awscli --upgrade --quiet
              build:
                commands:
                  - aws cloudformation validate-template --template-body file://${TemplateFileLocation}
  TestBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Ref TestProjectName
      Description: build project to validate our CF Template
      ServiceRole: !GetAtt  CodeExecutionRole.Arn
      Artifacts:
          Type: CODEPIPELINE
      Environment:
          Type: LINUX_CONTAINER
          ComputeType: BUILD_GENERAL1_SMALL
          Image: aws/codebuild/standard:4.0
          PrivilegedMode: true  
      Source:
          Type: CODEPIPELINE
          BuildSpec: !Sub |
            version: 0.2
            phases:
              install:
                commands:
                  - pip3 install awscli --upgrade --quiet
              build:
                commands:
                  - aws cloudformation wait stack-create-complete --stack-name ${ChildStackName}
######
######
Outputs:
  BucketName:
    Value: !Ref Bucket 
  CloudFormationExecutionRole:
    Value: !Ref CloudFormationExecutionRole
  CodeExecutionRole:
    Value: !Ref CodeExecutionRole
  CodePipeline:
    Value: !Ref CodePipeline