AWSTemplateFormatVersion: 2010-09-09
Description: "Creates an IAM user for Stelligent-U Topic 3: IAM Practice 3.1.4"
Resources: 
  iamRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: bgariamlabrole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/IAMReadOnlyAccess
  LabIAMRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: bgariamrole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/IAMReadOnlyAccess
        - arn:aws:iam::aws:policy/AmazonEC2ReadOnlyAccess
Outputs:
  RoleARN:
    Description: The ARN of the created IAM policy
    Value: !GetAtt iamRole.Arn
    Export:
      Name: !Join [ "-", [ !Ref "AWS::StackName", RoleARN ] ]
  LabRoleARN:
    Description: The ARN of the created IAM policy
    Value: !GetAtt LabIAMRole.Arn
    Export:
      Name: !Join [ "-", [ !Ref "AWS::StackName", LabRoleARN ] ]