AWSTemplateFormatVersion: 2010-09-09
Description: "Creates EC2 resource for Stelligent-U Topic 5: VPC Practice 5.1.2"
Parameters: 
    LatestUbuntuAmiId:
        Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
        Default: '/aws/service/canonical/ubuntu/server/18.04/stable/current/amd64/hvm/ebs-gp2/ami-id'
    LatestWindows2016AmiId:
        Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
        Default: '/aws/service/ami-windows-latest/Windows_Server-2016-English-Full-Base'
    LatestWindows2012R2AmiId:
        Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
        Default: '/aws/service/ami-windows-latest/Windows_Server-2012-R2_RTM-English-64Bit-Base'
    EC2KeyPairName:
      Description: 'The key to use for the instance'
      Type: String
      Default: ''
Resources: 
  labRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: bgarec2labrole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'
  labInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles:
        - !Ref labRole
  EC2Template:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: EC22012R2
      LaunchTemplateData: 
        KeyName: !Ref EC2KeyPairName
        InstanceType: t2.micro
        IamInstanceProfile:
          Name: !Ref labInstanceProfile
        Monitoring: 
          Enabled: true
        NetworkInterfaces:
          - SubnetId: !ImportValue bgar-lab-subnet-id
            DeviceIndex: 0
            Groups:
              - !Ref EC2SCG
    Metadata:
      AWS::CloudFormation::Init: 
        configSets: 
          cw_install:
            - "prep_cw_agent"
            - "install_collectd"
            - "install_cw_agent"
            - "run_cw_agent"
        prep_cw_agent:
          commands: 
            create_work_dir: 
              command: "mkdir /work"
              cwd: "~"
            download_cw_agent: 
              command: "wget https://s3.amazonaws.com/amazoncloudwatch-agent/ubuntu/amd64/latest/amazon-cloudwatch-agent.deb"
              cwd: "/work"
            download_cw_agent_config: 
              command: "curl https://us-east-1-324320755747-elpollolocodude.s3.amazonaws.com/config.json -o config.json"
              cwd: "/work"
            update_apt: 
              command: "apt-get update"
              cwd: "/work"
        install_collectd:
          commands:
            install_collectd_pkg: 
              command: "apt-get install collectd -y"
              cwd: "/work"
        install_cw_agent:
          commands:
            install_cw_agent: 
              command: ["dpkg", "-i", "-E", "./amazon-cloudwatch-agent.deb"]
              cwd: "/work"
        run_cw_agent:
          commands:
            run_cw_agent: 
              command: ["/opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl", "-a", "fetch-config", "-m", "ec2", "-s", "-c", "file:/work/config.json"]
              cwd: "/work"
  UbuntuInstance:
    Type: AWS::EC2::Instance
    CreationPolicy:
      ResourceSignal:    
        Count: 1
        Timeout: PT5M
    Properties:
      LaunchTemplate: 
        LaunchTemplateId: !Ref EC2Template
        Version: !GetAtt EC2Template.LatestVersionNumber
      ImageId: !Ref LatestUbuntuAmiId
      BlockDeviceMappings:
        - DeviceName: /dev/xvdb
          Ebs: 
            Encrypted: true
            VolumeSize: 25
            VolumeType: gp2
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -xe
          # Prep
          apt-get update -y
          apt-get -y install python3-pip
          pip3 install https://s3.amazonaws.com/cloudformation-examples/aws-cfn-bootstrap-py3-latest.tar.gz
          
          # Run init
          cfn-init -v --stack ${AWS::StackId} --resource EC2Template --configsets cw_install --region ${AWS::Region}

          # Setup EBS Volume as /data mount
          mkfs -t xfs /dev/xvdb
          mkdir /data
          mount /dev/xvdb
          echo "/dev/xvdb    /data   xfs    defaults    1 1" >> /etc/fstab

          # Send completion signal
          cfn-signal -e $? --stack ${AWS::StackId} --resource EC2Template --region ${AWS::Region}
      Tags: 
        - Key: Name
          Value: bgar-Ubuntu-lab51
        - Key: user
          Value: brandon.garcia.labs
        - Key: stelligent-u-lesson
          Value: '5.2'
        - Key: stelligent-u-lab
          Value: '5.2.1'
  EIP:
    Type: AWS::EC2::EIP
    Properties: 
      Domain: vpc
      InstanceId: !Ref UbuntuInstance
      Tags: 
        - Key: user
          Value: brandon.garcia.labs
        - Key: stelligent-u-lesson
          Value: '5.2'
        - Key: stelligent-u-lab
          Value: '5.2.1'
  EC2SCG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: bgar-stelu-l-512
      GroupDescription: 'bgar stelu sg'
      VpcId: !ImportValue bgar-lab-vpc-id
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 24.32.231.81/32
        - IpProtocol: icmp
          FromPort: -1
          ToPort: -1
          CidrIp: 24.32.231.81/32
      SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: 0
          ToPort: 65535
          CidrIp: 0.0.0.0/0
        - IpProtocol: icmp
          FromPort: -1
          ToPort: -1
          CidrIp: 0.0.0.0/0
      Tags: 
        - Key: user
          Value: brandon.garcia.labs
        - Key: stelligent-u-lesson
          Value: '5.2'
        - Key: stelligent-u-lab
          Value: '5.2.1'
Outputs:
  UbuntuInstanceId:
    Description: The Ubuntu instance id
    Value: !Ref UbuntuInstance
  UbuntuPrivateIp:
    Description: The Ubuntu instance private ip
    Value: !GetAtt UbuntuInstance.PrivateIp
  UbuntuEIP:
    Description: The Ubuntu instance elastic ip
    Value: !Ref EIP
  InstanceRoleArn:
    Description: The instance role
    Value: !Ref labRole
  InstanceProfile:
    Description: The instance profile
    Value: !Ref labInstanceProfile