AWSTemplateFormatVersion: 2010-09-09
Description:  "Creates a linked IAM user and policy for Stelligent-U Topic 1: CF Practice 1.2.2"
Parameters: 
  UserName:
    Description: The name of the bucket
    Type: String
    Default: ''
Resources: 
  TheUser:
    Type: AWS::IAM::User
    Properties: 
      UserName: !Ref UserName
  ThePolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties: 
      Description: Allows read to all S3 buckets and objects within this AWS account
      ManagedPolicyName: S3Read
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - s3:ListBucket
              - s3:GetObject*
            Resource:
              - arn:aws:s3:::*
              - arm:aws:s3:::*/*
      Users: 
        - !Ref TheUser
Outputs:
  PolicyARN:
    Description: The ARN of the created IAM policy
    Value: !Ref ThePolicy
    Export:
      Name: !Join [ "-", [ !Ref "AWS::StackName", PolicyARN ] ]