AWSTemplateFormatVersion: 2010-09-09
Description: "Creates VPC peering resource for Stelligent-U Topic 4: VPC Practice 4.2"
Parameters: 
  PeerRegion:
    Description: "The region of the peer vpc"
    Type: String
    Default: ''
  PeerVPC:
    Description: "The peer vpc id"
    Type: String
    Default: ''
  VPCId:
    Description: "The ID of the local vpc"
    Type: String
    Default: ''
Resources: 
  Peering:
    Type: AWS::EC2::VPCPeeringConnection
    Properties: 
      PeerRegion: !Ref PeerRegion
      PeerVpcId: !Ref PeerVPC
      Tags: 
        - Key: user
          Value: brandon.garcia.labs
        - Key: stelligent-u-lesson
          Value: '4.2'
        - Key: stelligent-u-lab
          Value: '4.2'
      VpcId: !Ref VPCId
