AWSTemplateFormatVersion: 2010-09-09
Description: "Creates private VPC resource for Stelligent-U Topic 4: VPC Practice 4.2"
Parameters: 
  VPCCidr:
    Description: cidr block of the VPC
    Type: String
    Default: ''
  SubnetCidr:
    Description: cidr block of the subnet
    Type: String
    Default: ''
  PrivateSubnetCidr:
    Description: cidr block of the private subnet
    Type: String
    Default: ''
  PeerVPCCidr:
    Description: cidr block of the peer vpc
    Type: String
    Default: ''
Resources: 
  VPC:
    Type: AWS::EC2::VPC
    Properties: 
      CidrBlock: !Ref VPCCidr
      EnableDnsHostnames: true
      EnableDnsSupport: true
      Tags: 
        - Key: user
          Value: brandon.garcia.labs
        - Key: stelligent-u-lesson
          Value: '4.2'
        - Key: stelligent-u-lab
          Value: '4.2'
  PrivateSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: us-east-2a
      MapPublicIpOnLaunch: true
      VpcId: !Ref VPC
      CidrBlock: !Ref PrivateSubnetCidr
      Tags: 
        - Key: user
          Value: brandon.garcia.labs
        - Key: stelligent-u-lesson
          Value: '4.2'
        - Key: stelligent-u-lab
          Value: '4.2'
  VPCRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags: 
        - Key: user
          Value: brandon.garcia.labs
        - Key: stelligent-u-lesson
          Value: '4.2'
        - Key: stelligent-u-lab
          Value: '4.2'
  RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PrivateSubnet
      RouteTableId: !Ref VPCRouteTable
  PrivateACL:
    Type: AWS::EC2::NetworkAcl
    Properties: 
      Tags: 
        - Key: user
          Value: brandon.garcia.labs
        - Key: stelligent-u-lesson
          Value: '4.2'
        - Key: stelligent-u-lab
          Value: '4.2'
      VpcId: !Ref VPC
  PrivateSSHInRule:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: !Ref PrivateACL
      RuleNumber: 100
      Protocol: 6
      RuleAction: allow
      CidrBlock: !Ref SubnetCidr
      PortRange:
        From: 22
        To: 22
  PrivateICMPInRule:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: !Ref PrivateACL
      RuleNumber: 101
      Icmp: 
        Code: -1
        Type: -1
      Protocol: 1
      RuleAction: allow
      CidrBlock: !Ref SubnetCidr
  PrivateAllowRemoteVPCInRule:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: !Ref PrivateACL
      RuleNumber: 102
      Protocol: -1
      RuleAction: allow
      CidrBlock: !Ref PeerVPCCidr
  PrivateAllOutRule:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: !Ref PrivateACL
      RuleNumber: 101
      Protocol: -1
      Egress: true
      RuleAction: allow
      CidrBlock: !Ref SubnetCidr
  PrivateAllPeerOutRule:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: !Ref PrivateACL
      RuleNumber: 102
      Protocol: -1
      Egress: true
      RuleAction: allow
      CidrBlock: !Ref PeerVPCCidr
  PrivateACLAssociation:
    Type: AWS::EC2::SubnetNetworkAclAssociation
    Properties: 
      NetworkAclId: !Ref PrivateACL
      SubnetId: !Ref PrivateSubnet
Outputs:
  VPCID:
    Description: The ID of the VPC
    Value: !Ref VPC
    Export:
      Name: bgar-lab-vpc-id
  PrivateSubnetID:
    Description: The ID of the subnet
    Value: !Ref PrivateSubnet
    Export:
      Name: bgar-lab-private-subnet-id