AWSTemplateFormatVersion: 2010-09-09
Description: "Creates EC2 resource for Stelligent-U Topic 5: VPC Practice 5.1.2"
Parameters: 
    LatestUbuntuAmiId:
        Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
        Default: '/aws/service/canonical/ubuntu/server/18.04/stable/current/amd64/hvm/ebs-gp2/ami-id'
    LatestWindows2016AmiId:
        Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
        Default: '/aws/service/ami-windows-latest/Windows_Server-2016-English-Full-Base'
    LatestWindows2012R2AmiId:
        Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
        Default: '/aws/service/ami-windows-latest/Windows_Server-2012-R2_RTM-English-64Bit-Base'
    EC2KeyPairName:
      Description: 'The key to use for the instance'
      Type: String
      Default: ''
Resources: 
  labRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: bgarec2labrole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'
  labInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles:
        - !Ref labRole
  EC2Template:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: EC22012R2
      LaunchTemplateData: 
        KeyName: !Ref EC2KeyPairName
        InstanceType: t2.micro
        IamInstanceProfile:
          Name: !Ref labRole
        Monitoring: 
          Enabled: true
        NetworkInterfaces:
          - SubnetId: !ImportValue bgar-lab-subnet-id
            DeviceIndex: 0
            Groups:
              - !Ref EC2SCG
        UserData: IyEvYmluL2Jhc2gKd2dldCBodHRwczovL3MzLmFtYXpvbmF3cy5jb20vYW1hem9uY2xvdWR3YXRjaC1hZ2VudC91YnVudHUvYW1kNjQvbGF0ZXN0L2FtYXpvbi1jbG91ZHdhdGNoLWFnZW50LmRlYgpzdWRvIGRwa2cgLWkgLUUgLi9hbWF6b24tY2xvdWR3YXRjaC1hZ2VudC5kZWIKc3VkbyAvb3B0L2F3cy9hbWF6b24tY2xvdWR3YXRjaC1hZ2VudC9iaW4vYW1hem9uLWNsb3Vkd2F0Y2gtYWdlbnQtY3RsIC1hIGZldGNoLWNvbmZpZyAtbSBlYzIgLXMgLWMgZmlsZTovb3B0L2F3cy9hbWF6b24tY2xvdWR3YXRjaC1hZ2VudC9ldGMvY29uZmlnLmpzb24=
  UbuntuInstance:
    Type: AWS::EC2::Instance
    Properties:
      LaunchTemplate: 
        LaunchTemplateId: !Ref EC2Template
        Version: !GetAtt EC2Template.LatestVersionNumber
      ImageId: !Ref LatestUbuntuAmiId
      Tags: 
        - Key: Name
          Value: bgar-Ubuntu-lab51
        - Key: user
          Value: brandon.garcia.labs
        - Key: stelligent-u-lesson
          Value: '5.2'
        - Key: stelligent-u-lab
          Value: '5.2.1'
  EIP:
    Type: AWS::EC2::EIP
    Properties: 
      Domain: vpc
      InstanceId: !Ref UbuntuInstance
      Tags: 
        - Key: user
          Value: brandon.garcia.labs
        - Key: stelligent-u-lesson
          Value: '5.2'
        - Key: stelligent-u-lab
          Value: '5.2.1'
  EC2SCG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: bgar-stelu-l-512
      GroupDescription: 'bgar stelu sg'
      VpcId: !ImportValue bgar-lab-vpc-id
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 24.32.231.81/32
        - IpProtocol: icmp
          FromPort: -1
          ToPort: -1
          CidrIp: 24.32.231.81/32
      SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: 0
          ToPort: 65535
          CidrIp: 0.0.0.0/0
        - IpProtocol: icmp
          FromPort: -1
          ToPort: -1
          CidrIp: 0.0.0.0/0
      Tags: 
        - Key: user
          Value: brandon.garcia.labs
        - Key: stelligent-u-lesson
          Value: '5.2'
        - Key: stelligent-u-lab
          Value: '5.2.1'

Outputs:
  UbuntuInstanceId:
    Description: The Ubuntu instance id
    Value: !Ref UbuntuInstance
  UbuntuPrivateIp:
    Description: The Ubuntu instance private ip
    Value: !GetAtt UbuntuInstance.PrivateIp
  UbuntuEIP:
    Description: The Ubuntu instance elastic ip
    Value: !Ref EIP
  InstanceRoleArn:
    Description: The instance role
    Value: !Ref labRole
  InstanceProfile:
    Description: The instance role
    Value: !Ref labInstanceProfile