AWSTemplateFormatVersion: 2010-09-09
Description:  "Creates a linked IAM user and policy for Stelligent-U Topic 1: CF Practice 1.2.3"
Parameters: 
  UserName:
    Description: The name of the bucket
    Type: String
    Default: ''
  PolicyStack:
    Description: The stack ID of the policy stack
    Type: String
    Default: ''
Resources: 
  TheUser:
    Type: AWS::IAM::User
    Properties: 
      UserName: !Ref UserName
      ManagedPolicyArns:
        - !ImportValue 
          Fn::Sub: '${PolicyStack}-PolicyARN'