AWSTemplateFormatVersion: 2010-09-09
Description: "Creates EC2 resource for Stelligent-U Topic 5: VPC Practice 6.1.2"
Parameters: 
    LatestUbuntuAmiId:
        Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
        Default: '/aws/service/canonical/ubuntu/server/18.04/stable/current/amd64/hvm/ebs-gp2/ami-id'
    LatestWindows2016AmiId:
        Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
        Default: '/aws/service/ami-windows-latest/Windows_Server-2016-English-Full-Base'
    LatestWindows2012R2AmiId:
        Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
        Default: '/aws/service/ami-windows-latest/Windows_Server-2012-R2_RTM-English-64Bit-Base'
    LatestDebianAmiId:
        Type: String
        Default: ''
    EC2KeyPairName:
      Description: 'The key to use for the instance'
      Type: String
      Default: ''
Resources: 
  labRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: bgarec2labrole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'
  labInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles:
        - !Ref labRole
  EC2SCG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: bgar-stelu-l-512
      GroupDescription: 'bgar stelu sg'
      VpcId: !ImportValue bgar-lab-vpc-id
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 24.32.231.81/32
        - IpProtocol: icmp
          FromPort: -1
          ToPort: -1
          CidrIp: 24.32.231.81/32
      SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: 0
          ToPort: 65535
          CidrIp: 0.0.0.0/0
        - IpProtocol: icmp
          FromPort: -1
          ToPort: -1
          CidrIp: 0.0.0.0/0
      Tags: 
        - Key: user
          Value: brandon.garcia.labs
        - Key: stelligent-u-lesson
          Value: '6.1'
        - Key: stelligent-u-lab
          Value: '6.1.1'
  ASLaunchConfig:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      AssociatePublicIpAddress: true
      IamInstanceProfile: !Ref labInstanceProfile
      ImageId: !Ref LatestDebianAmiId
      InstanceMonitoring: true
      InstanceType: t2.small
      KeyName: !Ref EC2KeyPairName
      SecurityGroups:
        - !Ref EC2SCG
  ASGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      LaunchConfigurationName: !Ref ASLaunchConfig
      MaxSize: 1
      MinSize: 1
      DesiredCapacity: 1
      VPCZoneIdentifier: 
        - !ImportValue bgar-lab-subnet-id
      Tags: 
        - Key: user
          Value: brandon.garcia.labs
          PropagateAtLaunch: true
        - Key: stelligent-u-lesson
          Value: '6.1'
          PropagateAtLaunch: true
        - Key: stelligent-u-lab
          Value: '6.1.1'
          PropagateAtLaunch: true
Outputs:
  InstanceRoleArn:
    Description: The instance role
    Value: !Ref labRole
  InstanceProfile:
    Description: The instance profile
    Value: !Ref labInstanceProfile