AWSTemplateFormatVersion: 2010-09-09
Description: "Creates CodePipeline resources for Stelligent-U Topic 12: CodePipeline Practice 12.1.1"
######
######
Parameters: 
  BucketName:
    Type: String 
    Default: ''
    Description: The name of the bucket to house pipeline execution state
  GitHubOwner:
    Description: The user to pull the repository
    Type: String
    Default: ''
  Branch:
    Description: The branch to pull for pipeline execution
    Type: String
    Default: ''
  RepositoryName:
    Description:  The repository to pull for pipeline execution
    Type: String
    Default: ''
######
######
Resources: 
  Bucket:
    Type: AWS::S3::Bucket
    Properties: 
      AccessControl: BucketOwnerFullControl
      BucketName: !Ref BucketName
  CodeExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codepipeline.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSCloudFormationFullAccess
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
      Policies:
        - PolicyName: AllowIamActions
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - iam:GetRole
                  - iam:PassRole
                Resource: !GetAtt CloudFormationExecutionRole.Arn
  CloudFormationExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - cloudformation.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
  CodePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: !Sub bgar-pipeline
      RoleArn: !GetAtt CodeExecutionRole.Arn
      ArtifactStore:
        Type: S3
        Location: !Ref Bucket
      Stages: 
        - Name: source
          Actions:
            - Name: PullSource
              ActionTypeId: 
                Category: Source
                Owner: ThirdParty
                Provider: GitHub
                Version: 1
              OutputArtifacts:
                - Name: LabSource
              RunOrder: 1
              Configuration: 
                Owner: !Ref GitHubOwner
                Repo: !Ref RepositoryName
                Branch: !Ref Branch
                OAuthToken: "{{resolve:secretsmanager:bgar-gh-token:SecretString:::7de73ed0-8301-4895-99b0-b6dda7da39d9}}"
                PollForSourceChanges: true
        - Name: build
          Actions:
            - Name: Validation
              ActionTypeId: 
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: 1
              InputArtifacts: 
                - Name: LabSource
              RunOrder: 2
              Configuration: 
                ProjectName: !Ref ProjectName
        - Name: deploy
          Actions:
            - Name: CreateStack
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: 1
              InputArtifacts: 
                - Name: LabSource
              Configuration:
                ParameterOverrides: '{"BucketNameParameter": "bgar-child-bucket-pipeline"}'
                ActionMode: CREATE_UPDATE
                RoleArn: !GetAtt CloudFormationExecutionRole.Arn
                StackName: bgar-pipeline-12-1-1
                TemplatePath: LabSource::12-codepipeline/bucket.yaml
      RestartExecutionOnUpdate: false
  BuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Ref ProjectName
      Description: build project to validate our CF Template
      ServiceRole: !GetAtt  CodeExecutionRole.Arn
      Artifacts:
          Type: NO_ARTIFACTS
      Environment:
          Type: LINUX_CONTAINER
          ComputeType: BUILD_GENERAL1_SMALL
          Image: aws/codebuild/standard:4.0
          PrivilegedMode: true  
      Source:
          Location: https://git-codecommit.eu-central-1.amazonaws.com/v1/repos/test-lint
          Type: CODEPIPELINE
          BuildSpec: |
            version: 0.2
            phases:
              install:
                runtime-versions:
                    ruby: 2.6    
                commands:
                - pip3 install awscli --upgrade --quiet
              build:
                commands:
                - aws cloudformation validate-template --template-body ./12-codepipeline/lab12-1-2/template.yml
                  TimeoutInMinutes: 15
######
######
Outputs:
  BucketName:
    Value: !Ref Bucket 
  CloudFormationExecutionRole:
    Value: !Ref CloudFormationExecutionRole
  CodePipelineExecutionRole:
    Value: !Ref CodePipelineExecutionRole
  CodePipeline:
    Value: !Ref CodePipeline