AWSTemplateFormatVersion: 2010-09-09
Description: 'Creates log resources for Stelligent-U Topic 8: Lab 8.2.1'
Parameters: 
  BucketName:
    Description: 'The name of the log group'
    Type: String
    Default: ''
Resources: 
  s3Bucket:
    Type: AWS::S3::Bucket
    Properties: 
      AccessControl: LogDeliveryWrite
      BucketName: !Ref BucketName
      Tags: 
        - Key: user
          Value: brandon.garcia.labs
        - Key: stelligent-u-lesson
          Value: '8.2'
        - Key: stelligent-u-lab
          Value: '8.2.1'
Outputs:
  Bucket:
    Description: The bucket
    Value: !Ref s3Bucket