AWSTemplateFormatVersion: 2010-09-09
Description: "Creates VPC resource for Stelligent-U Topic 4: VPC Practice 4.1"
Parameters: 
  VPCCidr:
    Description: cidr block of the VPC
    Type: String
    Default: ''
  SubnetCidr:
    Description: cidr block of the subnet
    Type: String
    Default: ''
Resources: 
  VPC:
    Type: AWS::EC2::VPC
    Properties: 
      CidrBlock: !Ref VPCCidr
      EnableDnsHostnames: true
      EnableDnsSupport: true
      Tags: 
        - Key: user
          Value: brandon.garcia.labs
        - Key: stelligent-u-lesson
          Value: '4.1'
        - Key: stelligent-u-lab
          Value: '4.1.1'
  Subnet:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: us-east-1a
      MapPublicIpOnLaunch: true
      VpcId: !Ref VPC
      CidrBlock: !Ref SubnetCidr
      Tags: 
        - Key: user
          Value: brandon.garcia.labs
        - Key: stelligent-u-lesson
          Value: '4.1'
        - Key: stelligent-u-lab
          Value: '4.1.1'
  IGW:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags: 
        - Key: user
          Value: brandon.garcia.labs
        - Key: stelligent-u-lesson
          Value: '4.1'
        - Key: stelligent-u-lab
          Value: '4.1.1'
  IGWAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref IGW
  VPCRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags: 
        - Key: user
          Value: brandon.garcia.labs
        - Key: stelligent-u-lesson
          Value: '4.1'
        - Key: stelligent-u-lab
          Value: '4.1.1'
  VPCDefaultRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref VPCRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref IGW
  RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref Subnet
      RouteTableId: !Ref VPCRouteTable
Outputs:
  VPCID:
    Description: The ID of the VPC
    Value: !Ref VPC
    Export:
      Name: bgar-lab-vpc-id
  SubnetID:
    Description: The ID of the subnet
    Value: !Ref Subnet
    Export:
      Name: bgar-lab-subnet-id