AWSTemplateFormatVersion: 2010-09-09
Description: "Creates an IAM user for Stelligent-U Topic 3: IAM Practice 3.3"
Resources: 
  FirstBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Join ['-', [!Ref AWS::Region, !Ref AWS::AccountId, 'thebucketbg']]
  SecondBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Join ['-', [!Ref AWS::Region, !Ref AWS::AccountId, 'thebucketgg']]
  iamRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: bgariamlabrole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS: arn:aws:iam::324320755747:user/brandon.garcia.labs
            Action:
              - 'sts:AssumeRole'
  iamPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties: 
      Description: "Managed policy for bgar IAM lab"
      ManagedPolicyName: bgariamlab
      PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - s3:*
            Resource:
            - !GetAtt FirstBucket.Arn
            - !Join ['', [!GetAtt FirstBucket.Arn, '/*']]
          - Effect: Allow
            Action:
            - s3:List*
            - s3:Get*
            Resource:
            - !GetAtt FirstBucket.Arn
            - !Join ['', [!GetAtt FirstBucket.Arn, '/*']]
            Condition:
              StringEquals:
                's3:prefix': 'lebowski/'
          - Effect: Deny
            Action:
            - s3:List*
            - s3:Get*
            Resource:
            - !GetAtt FirstBucket.Arn
            - !Join ['', [!GetAtt FirstBucket.Arn, '/*']]
            Condition:
              StringNotEquals:
                's3:prefix': 'lebowski/'
      Roles: 
        - !Ref iamRole
Outputs:
  RoleARN:
    Description: The ARN of the created IAM policy
    Value: !GetAtt iamRole.Arn
    Export:
      Name: !Join [ "-", [ !Ref "AWS::StackName", RoleARN ] ]